import { ImageResponse } from "next/og";

/**
 * Dynamic favicon — the lowercase b in red on paper. Generated by
 * Next.js ImageResponse so the typography renders consistently
 * across browser tabs without needing an external font fetch.
 *
 * Used for /favicon (32x32). Sized for browser tab usage.
 */
export const size = { width: 32, height: 32 };
export const contentType = "image/png";

export default function Icon() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          background: "#F3EFE6",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontFamily: "system-ui",
          fontSize: 30,
          fontWeight: 900,
          color: "#C4472E",
          letterSpacing: "-0.04em",
          paddingBottom: 4,
        }}
      >
        b
      </div>
    ),
    { ...size }
  );
}
